"""This ui has been generated by QT Designer as specified below. Not for commercial use. """

from PyQt5.QtWidgets import QPushButton
from PyQt5.QtWidgets import QLabel
from PyQt5.QtWidgets import QLineEdit
from PyQt5.QtWidgets import QWidget
from PyQt5.QtWidgets import QHBoxLayout
from PyQt5.QtWidgets import QVBoxLayout
from PyQt5.QtWidgets import QTabWidget
from PyQt5.QtCore import QCoreApplication
from PyQt5.QtCore import QMetaObject
from PyQt5.QtCore import QRect
from PyQt5.QtGui import QFont
from PyQt5.QtGui import QCursor
from PyQt5.QtCore import Qt

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitledWmqZpV.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(652, 407)
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 691, 471))
        self.tabWidget.setCursor(QCursor(Qt.ArrowCursor))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_convert = QLabel(self.tab)
        self.label_convert.setObjectName(u"label_convert")
        self.label_convert.setGeometry(QRect(40, 30, 121, 31))
        font = QFont()
        font.setPointSize(10)
        self.label_convert.setFont(font)
        self.horizontalLayoutWidget = QWidget(self.tab)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(70, 70, 501, 51))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.line_edit_file = QLineEdit(self.horizontalLayoutWidget)
        self.line_edit_file.setObjectName(u"line_edit_file")

        self.horizontalLayout.addWidget(self.line_edit_file)

        self.button_file = QPushButton(self.horizontalLayoutWidget)
        self.button_file.setObjectName(u"button_file")

        self.horizontalLayout.addWidget(self.button_file)

        self.horizontalLayoutWidget_2 = QWidget(self.tab)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(70, 180, 501, 51))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.line_edit_folder = QLineEdit(self.horizontalLayoutWidget_2)
        self.line_edit_folder.setObjectName(u"line_edit_folder")

        self.horizontalLayout_2.addWidget(self.line_edit_folder)

        self.button_folder = QPushButton(self.horizontalLayoutWidget_2)
        self.button_folder.setObjectName(u"button_folder")

        self.horizontalLayout_2.addWidget(self.button_folder)

        self.label_folder = QLabel(self.tab)
        self.label_folder.setObjectName(u"label_folder")
        self.label_folder.setGeometry(QRect(40, 140, 121, 31))
        self.label_folder.setFont(font)
        self.horizontalLayoutWidget_3 = QWidget(self.tab)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(330, 260, 195, 41))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.button_run = QPushButton(self.horizontalLayoutWidget_3)
        self.button_run.setObjectName(u"button_run")

        self.horizontalLayout_3.addWidget(self.button_run)

        self.button_clear = QPushButton(self.horizontalLayoutWidget_3)
        self.button_clear.setObjectName(u"button_clear")

        self.horizontalLayout_3.addWidget(self.button_clear)

        self.horizontalLayoutWidget_6 = QWidget(self.tab)
        self.horizontalLayoutWidget_6.setObjectName(u"horizontalLayoutWidget_6")
        self.horizontalLayoutWidget_6.setGeometry(QRect(40, 260, 241, 41))
        self.horizontalLayout_6 = QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_filename = QLabel(self.horizontalLayoutWidget_6)
        self.label_filename.setObjectName(u"label_filename")
        self.label_filename.setFont(font)

        self.horizontalLayout_6.addWidget(self.label_filename)

        self.line_edit_filename = QLineEdit(self.horizontalLayoutWidget_6)
        self.line_edit_filename.setObjectName(u"line_edit_filename")

        self.horizontalLayout_6.addWidget(self.line_edit_filename)

        self.label_status = QLabel(self.tab)
        self.label_status.setObjectName(u"label_status")
        self.label_status.setGeometry(QRect(440, 330, 181, 31))
        self.label_status.setFont(font)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.apply_settings = QPushButton(self.tab_2)
        self.apply_settings.setObjectName(u"apply_settings")
        self.apply_settings.setGeometry(QRect(260, 290, 111, 31))
        self.horizontalLayoutWidget_4 = QWidget(self.tab_2)
        self.horizontalLayoutWidget_4.setObjectName(u"horizontalLayoutWidget_4")
        self.horizontalLayoutWidget_4.setGeometry(QRect(70, 200, 501, 51))
        self.horizontalLayout_4 = QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.line_edit_poppler = QLineEdit(self.horizontalLayoutWidget_4)
        self.line_edit_poppler.setObjectName(u"line_edit_poppler")

        self.horizontalLayout_4.addWidget(self.line_edit_poppler)

        self.button_poppler = QPushButton(self.horizontalLayoutWidget_4)
        self.button_poppler.setObjectName(u"button_poppler")

        self.horizontalLayout_4.addWidget(self.button_poppler)

        self.label_poppler = QLabel(self.tab_2)
        self.label_poppler.setObjectName(u"label_poppler")
        self.label_poppler.setGeometry(QRect(40, 160, 201, 31))
        self.label_poppler.setFont(font)
        self.label_pytesseract = QLabel(self.tab_2)
        self.label_pytesseract.setObjectName(u"label_pytesseract")
        self.label_pytesseract.setGeometry(QRect(40, 30, 191, 31))
        self.label_pytesseract.setFont(font)
        self.horizontalLayoutWidget_5 = QWidget(self.tab_2)
        self.horizontalLayoutWidget_5.setObjectName(u"horizontalLayoutWidget_5")
        self.horizontalLayoutWidget_5.setGeometry(QRect(70, 80, 501, 51))
        self.horizontalLayout_5 = QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.line_edit_pytesseract = QLineEdit(self.horizontalLayoutWidget_5)
        self.line_edit_pytesseract.setObjectName(u"line_edit_pytesseract")

        self.horizontalLayout_5.addWidget(self.line_edit_pytesseract)

        self.button_pytesseract = QPushButton(self.horizontalLayoutWidget_5)
        self.button_pytesseract.setObjectName(u"button_pytesseract")

        self.horizontalLayout_5.addWidget(self.button_pytesseract)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.verticalLayoutWidget = QWidget(self.tab_3)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(30, 40, 581, 271))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_user_guide = QLabel(self.verticalLayoutWidget)
        self.label_user_guide.setObjectName(u"label_user_guide")
        self.label_user_guide.setFont(font)
        self.label_user_guide.setCursor(QCursor(Qt.IBeamCursor))
        self.label_user_guide.setWordWrap(True)
        self.label_user_guide.setTextInteractionFlags(
            Qt.LinksAccessibleByMouse | Qt.TextSelectableByMouse
        )

        self.verticalLayout.addWidget(self.label_user_guide)

        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Dialog)

        self.tabWidget.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(Dialog)

    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(
            QCoreApplication.translate("Dialog", u"PDF Converter", None)
        )
        self.label_convert.setText(
            QCoreApplication.translate("Dialog", u"File to convert:", None)
        )
        self.button_file.setText(QCoreApplication.translate("Dialog", u"Browse", None))
        self.button_folder.setText(
            QCoreApplication.translate("Dialog", u"Browse", None)
        )
        self.label_folder.setText(
            QCoreApplication.translate("Dialog", u"Output folder:", None)
        )
        self.button_run.setText(QCoreApplication.translate("Dialog", u"RUN", None))
        self.button_clear.setText(QCoreApplication.translate("Dialog", u"CLEAR", None))
        self.label_filename.setText(
            QCoreApplication.translate("Dialog", u"Filename:", None)
        )
        self.label_status.setText(
            QCoreApplication.translate("Dialog", u"Status: -", None)
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab),
            QCoreApplication.translate("Dialog", u"Convert", None),
        )
        self.apply_settings.setText(
            QCoreApplication.translate("Dialog", u"APPLY", None)
        )
        self.button_poppler.setText(
            QCoreApplication.translate("Dialog", u"Browse", None)
        )
        self.label_poppler.setText(
            QCoreApplication.translate("Dialog", u"Locate poppler bin folder:", None)
        )
        self.label_pytesseract.setText(
            QCoreApplication.translate("Dialog", u"Locate pytesseract.exe:", None)
        )
        self.button_pytesseract.setText(
            QCoreApplication.translate("Dialog", u"Browse", None)
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2),
            QCoreApplication.translate("Dialog", u"Settings", None),
        )
        self.label_user_guide.setText(
            QCoreApplication.translate(
                "Dialog",
                u"USER GUIDE:\n"
                "\n"
                "1. Install Google Tesseract OCR engine from: https://github.com/tesseract-ocr/tesseract\n"
                "2. Download poppler from: https://poppler.freedesktop.org/\n"
                "3. Go to the Settings tab and use Browse button to locate: tesseract.exe file and bin folder for poppler\n"
                "4. Go to the Convert tab and select the PDF file to convert, output folder where the files should be extracted into, and (optionally) filename of the output file\n"
                "5. Wait for the converter to be done, watch the status bar at the bottom of the Convert tab to be notified when the processing ends",
                None,
            )
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_3),
            QCoreApplication.translate("Dialog", u"Help", None),
        )

    # retranslateUi
